// 自动生成的HTML字符串常量
// 变量名: wifi_page_html
// 生成时间: 2025-10-07 10:49:15

const char* wifi_page_html =
        "<!DOCTYPE html><html lang=\\"zh-CN\\"><head><meta charset=\\"UTF-8\\"><"
        "meta name=\\"viewport\\" content=\\"width=device-width,initial-scale=1."
        "0\\"><title>智能传感器设备配网</title><style> *{margin:0;padding:0;box-sizing:bo"
        "rder-box;}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',"
        "Roboto,sans-serif;background:linear-gradient(135deg,#667eea 0%,#764ba2 "
        "100%);min-height:100vh;display:flex;align-items:center;justify-content:"
        "center;padding:20px;}.container{background:white;border-radius:20px;box"
        "-shadow:0 20px 40px rgba(0,0,0,0.1);padding:40px;width:100%;max-width:5"
        "00px;text-align:center;}.logo{width:80px;height:80px;background:linear-"
        "gradient(135deg,#667eea,#764ba2);border-radius:50%;margin:0 auto 20px;d"
        "isplay:flex;align-items:center;justify-content:center;font-size:32px;co"
        "lor:white;}h1{color:#333;margin-bottom:10px;font-size:28px;font-weight:"
        "600;}.subtitle{color:#666;margin-bottom:30px;font-size:16px;}.form-grou"
        "p{margin-bottom:20px;text-align:left;}label{display:block;margin-bottom"
        ":8px;color:#333;font-weight:500;font-size:14px;}input[type=\\"text\\"],"
        "input[type=\\"password\\"]{width:100%;padding:15px;border:2px solid #e1"
        "e5e9;border-radius:10px;font-size:16px;transition:border-color 0.3s eas"
        "e;background:#f8f9fa;}input[type=\\"text\\"]:focus,input[type=\\"passwo"
        "rd\\"]:focus{outline:none;border-color:#667eea;background:white;}.passw"
        "ord-toggle{position:relative;}.password-toggle button{position:absolute"
        ";right:15px;top:50%;transform:translateY(-50%);background:none;border:n"
        "one;color:#666;cursor:pointer;font-size:18px;padding:5px;}.btn{width:10"
        "0%;padding:15px;background:linear-gradient(135deg,#667eea,#764ba2);colo"
        "r:white;border:none;border-radius:10px;font-size:16px;font-weight:600;c"
        "ursor:pointer;transition:transform 0.2s ease,box-shadow 0.2s ease;margi"
        "n-top:10px;}.btn:hover{transform:translateY(-2px);box-shadow:0 10px 20p"
        "x rgba(102,126,234,0.3);}.btn:active{transform:translateY(0);}.btn:disa"
        "bled{opacity:0.6;cursor:not-allowed;transform:none;}.status{margin-top:"
        "20px;padding:15px;border-radius:10px;font-weight:500;display:none;}.sta"
        "tus.success{background:#d4edda;color:#155724;border:1px solid #c3e6cb;}"
        ".status.error{background:#f8d7da;color:#721c24;border:1px solid #f5c6cb"
        ";}.status.loading{background:#d1ecf1;color:#0c5460;border:1px solid #be"
        "e5eb;}.device-info{background:#f8f9fa;border-radius:10px;padding:20px;m"
        "argin-bottom:30px;text-align:left;}.device-info h3{color:#333;margin-bo"
        "ttom:15px;font-size:18px;}.info-item{display:flex;justify-content:space"
        "-between;margin-bottom:8px;font-size:14px;}.info-label{color:#666;font-"
        "weight:500;}.info-value{color:#333;font-family:monospace;}.steps{text-a"
        "lign:left;margin-bottom:30px;}.step{display:flex;align-items:center;mar"
        "gin-bottom:15px;font-size:14px;}.step-number{width:24px;height:24px;bac"
        "kground:#667eea;color:white;border-radius:50%;display:flex;align-items:"
        "center;justify-content:center;font-size:12px;font-weight:600;margin-rig"
        "ht:12px;flex-shrink:0;}.step-text{color:#666;}.loading-spinner{display:"
        "inline-block;width:20px;height:20px;border:2px solid #f3f3f3;border-top"
        ":2px solid #667eea;border-radius:50%;animation:spin 1s linear infinite;"
        "margin-right:10px;}@keyframes spin{0%{transform:rotate(0deg);}100%{tran"
        "sform:rotate(360deg);}}.hidden{display:none;}@media (max-width:480px){."
        "container{padding:30px 20px;margin:10px;}h1{font-size:24px;}}</style></"
        "head><body><div class=\\"container\\"><div class=\\"logo\\">📡</div><h1>"
        "智能传感器设备配网</h1><p class=\\"subtitle\\">请配置您的WiFi网络连接</p><div class=\\"de"
        "vice-info\\"><h3>设备信息</h3><div class=\\"info-item\\"><span class=\\"inf"
        "o-label\\">设备名称:</span><span class=\\"info-value\\">Esp-Sensor-Device</"
        "span></div><div class=\\"info-item\\"><span class=\\"info-label\\">设备类型"
        ":</span><span class=\\"info-value\\">传感器设备</span></div><div class=\\"in"
        "fo-item\\"><span class=\\"info-label\\">配网模式:</span><span class=\\"info"
        "-value\\">AP模式</span></div><div class=\\"info-item\\"><span class=\\"in"
        "fo-label\\">设备IP:</span><span class=\\"info-value\\">192.168.4.1</span>"
        "</div></div><div class=\\"steps\\"><div class=\\"step\\"><div class=\\""
        "step-number\\">1</div><div class=\\"step-text\\">确保设备已进入配网模式（LED快闪）</di"
        "v></div><div class=\\"step\\"><div class=\\"step-number\\">2</div><div "
        "class=\\"step-text\\">连接到设备的WiFi热点</div></div><div class=\\"step\\"><di"
        "v class=\\"step-number\\">3</div><div class=\\"step-text\\">输入您的WiFi账号和"
        "密码</div></div><div class=\\"step\\"><div class=\\"step-number\\">4</div"
        "><div class=\\"step-text\\">等待设备连接成功（LED常亮）</div></div></div><form id="
        "\\"wifiForm\\"><div class=\\"form-group\\"><label for=\\"ssid\\">WiFi网络"
        "名称 (SSID)</label><input type=\\"text\\" id=\\"ssid\\" name=\\"ssid\\" p"
        "laceholder=\\"请输入WiFi网络名称\\" required></div><div class=\\"form-group\\""
        "><label for=\\"password\\">WiFi密码</label><div class=\\"password-toggle"
        "\\"><input type=\\"password\\" id=\\"password\\" name=\\"password\\" pl"
        "aceholder=\\"请输入WiFi密码\\" required><button type=\\"button\\" onclick=\\"
        ""togglePassword()\\">👁️</button></div></div><button type=\\"submit\\" c"
        "lass=\\"btn\\" id=\\"submitBtn\\">开始配网</button></form><div id=\\"status"
        "\\" class=\\"status\\"></div></div><script> function togglePassword(){c"
        "onst passwordField = document.getElementById('password');const toggleBu"
        "tton = document.querySelector('.password-toggle button');if (passwordFi"
        "eld.type === 'password'){passwordField.type = 'text';toggleButton.textC"
        "ontent = '🙈';}else{passwordField.type = 'password';toggleButton.textCon"
        "tent = '👁️';}}function showStatus(message,type){const statusDiv = docum"
        "ent.getElementById('status');statusDiv.textContent = message;statusDiv."
        "className = `status ${type}`;statusDiv.style.display = 'block';}functio"
        "n hideStatus(){const statusDiv = document.getElementById('status');stat"
        "usDiv.style.display = 'none';}async function sendConfig(ssid,password){"
        "try{const response = await fetch('/config',{method:'POST',headers:{'Con"
        "tent-Type':'application/json'},body:JSON.stringify({ssid:ssid,password:"
        "password})});return await response.json();}catch (error){console.error("
        "'配网请求失败:',error);return{success:false,message:'网络连接失败，请重试'};}}document."
        "getElementById('wifiForm').addEventListener('submit',async function(eve"
        "nt){event.preventDefault();const ssid = document.getElementById('ssid')"
        ".value.trim();const password = document.getElementById('password').valu"
        "e;const submitBtn = document.getElementById('submitBtn');if (!ssid || !"
        "password){showStatus('请填写完整的WiFi信息','error');return;}submitBtn.disabled"
        " = true;submitBtn.innerHTML = '<span class=\\"loading-spinner\\"></span"
        ">配网中...';showStatus('正在配置WiFi网络，请稍候...','loading');try{const result = a"
        "wait sendConfig(ssid,password);if (result.success){showStatus('配网成功！设备正"
        "在连接WiFi，请等待LED常亮...','success');// 30秒倒计时 let countdown = 30;const time"
        "r = setInterval(() =>{showStatus(`配网成功！设备正在连接WiFi，请等待LED常亮... (${countd"
        "own}秒后自动关闭)`,'success');countdown--;if (countdown <= 0){clearInterval(t"
        "imer);showStatus('配网完成！如果设备LED常亮，说明连接成功。','success');}},1000);}else{sho"
        "wStatus(`配网失败:${result.message}`,'error');submitBtn.disabled = false;su"
        "bmitBtn.innerHTML = '重新配网';}}catch (error){showStatus('配网失败，请重试','error"
        "');submitBtn.disabled = false;submitBtn.innerHTML = '重新配网';}});document"
        ".addEventListener('DOMContentLoaded',function(){console.log('配网页面加载完成')"
        ";showStatus('已连接到设备，请输入WiFi信息开始配网','success');});</script></body></html"
        ">";
